ATT-27
openmrs/openmrs-module-attachments pull request #21
Opened 2018-07-08 18:40 UTC by ridmal

[ATT-24 ](https://issues.openmrs.org/browse/ATT-27) 

REST end point for file upload should allow to specify encounter

2018-07-17 13:38 UTC, dkayiwa commented
@mks-d what do you think of this?

2018-07-17 13:55 UTC, mks-d requested changes
@ridmal this is looking good, thank you.

But because there are several possible cases now, I would like to split this in several ad-hoc test methods:

1. `postAttachment_shouldUploadFileToVisit`
1. `postAttachment_shouldUploadFileAsEncounterless`
1. `postAttachment_shouldUploadFileToEncounter`

Would you mind doing this as your next commit on this branch?

2018-07-17 13:55 UTC, mks-d commented on omod-1.10/src/test/java/org/openmrs/module/attachments/rest/AttachmentController1_10Test.java
> +			Assert.assertNotNull(obs.getEncounter());
You should verify that it is the expected encounter, so the one whose UUID is `encounter.getUuid()`.

2018-07-18 08:07 UTC, mks-d reviewed
A few comments, but great!

Please resume based on my comments from yesterday, in particular to provide more test cases and split them in to separate methods.

2018-07-18 08:07 UTC, mks-d commented on omod-1.10/src/main/java/org/openmrs/module/attachments/rest/AttachmentResource1_10.java
> +				throw new IllegalRequestException("Visit and Encounter cannot be mismatched");
Make the error message:
>`"The specified encounter does not belong to the provided visit, upload aborted."`

2018-07-18 08:07 UTC, mks-d commented on omod-1.10/src/test/java/org/openmrs/module/attachments/rest/AttachmentController1_10Test.java
> +			Assert.assertNotNull(obs.getEncounter());
Please address my above comment.

2018-07-18 08:07 UTC, mks-d commented on omod-1.10/src/test/java/org/openmrs/module/attachments/rest/AttachmentController1_10Test.java
> +	public void postAttachment_shouldNotUploadFileWithDifferentEncounterAndVisit() throws Exception {
→ `postAttachment_shouldThrowWhenVisitAndEncounterDoNotMatch`

2018-07-19 04:20 UTC, ridmal commented
Thanks for your feedbacks @mks-d  and @dkayiwa . I update the PR .

2018-07-19 15:36 UTC, merged