Added french and spanish translation values
openmrs/openmrs-module-attachments pull request #44
Opened 2020-06-04 11:49 UTC by PremnishaTW

Added french and spanish translation values

2020-06-04 13:44 UTC, mks-d approved these changes
@brandones any chance you can check the 'es' translations?

2020-06-04 17:47 UTC, brandones commented
Sure. @PremnishaTW , can you post screenshots that capture the changes you made? The screenshots you posted are of the patient dashboard (which has one of those translation strings, but there are many others). I'm not familiar enough with the attachments module to know what all of these messages are.

2020-06-05 06:00 UTC, PremnishaTW commented
@brandones Please find the attachments for reference

French:
![image](https://user-images.githubusercontent.com/40290306/83840679-d4d6ef00-a71c-11ea-886f-e32e7c62a7d4.png)

Spanish:
![image](https://user-images.githubusercontent.com/40290306/83840828-297a6a00-a71d-11ea-8a43-2e84e80a8061.png)

2020-06-08 20:37 UTC, brandones requested changes
I couldn't find this in Transifex so I added the correct translations here.

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.dropzone.innerlabel=Haga clic o soltar un archivo aquí.
```suggestion
${project.parent.artifactId}.dropzone.innerlabel=Haga clic o deje un archivo aquí.
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.attachmentspage.commentTitle=Subtítulo
```suggestion
${project.parent.artifactId}.attachmentspage.commentTitle=Comentario
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.attachmentspage.clearFormsButton=formas claras
```suggestion
${project.parent.artifactId}.attachmentspage.clearFormsButton=Borrar todo
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.attachmentspage.delete.title=Eliminar archivo adjunto
```suggestion
${project.parent.artifactId}.attachmentspage.delete.title=Eliminar archivo adjunto
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.attachmentspage.delete.confirm=¿Seguro que desea eliminar este apego?
```suggestion
${project.parent.artifactId}.attachmentspage.delete.confirm=¿Seguro que desea eliminar este archivo adjunto?
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.attachmentspage.fileTitle=Expediente
```suggestion
${project.parent.artifactId}.attachmentspage.fileTitle=Archivo
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.fileUpload.attentionPastVisit=¡Atención! Los accesorios se pueden cargar en una visita pasado.
```suggestion
${project.parent.artifactId}.fileUpload.attentionPastVisit=¡Atención! Los accesorios estan cargando en una visita pasada.
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.thumbail.delete.success=La fijación se ha eliminado correctamente.
```suggestion
${project.parent.artifactId}.thumbail.delete.success=El archivo se ha eliminado correctamente.
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.thumbail.delete.error=Se ha producido un error y la unión no se pudo eliminar.
```suggestion
${project.parent.artifactId}.thumbail.delete.error=Se ha producido un error y el archivo adjunto no se pudo eliminar.
```

2020-06-08 20:37 UTC, brandones commented on api/src/main/resources/messages_es.properties
> +${project.parent.artifactId}.misc.label.enterCaption=Introducir un título
```suggestion
${project.parent.artifactId}.misc.label.enterCaption=Introducir un comentario
```

2020-06-09 08:44 UTC, merged

2020-06-09 17:35 UTC, brandones commented
@PremnishaTW  @mks-d Will these translations propagate to Transifex?