Attachments - Added configuration to the allowed file extension.
openmrs/openmrs-module-attachments pull request #61
Opened 2024-01-16 14:15 UTC by icrc-loliveira

2024-01-16 15:28 UTC, icrc-loliveira commented
@ibacher

2024-01-17 11:09 UTC, icrc-loliveira commented
@ibacher

2024-01-17 17:01 UTC, ibacher requested changes
Thanks @icrc-loliveira! A few small things to clean-up and this should be good.

2024-01-17 17:01 UTC, ibacher commented on api/src/main/java/org/openmrs/module/attachments/AttachmentsContext.java
> +	protected String[] getArrayGlobalProperty(String globalPropertyName, boolean required) {
Why do we have `boolean required` if it's always `false`?

2024-01-17 17:01 UTC, ibacher commented on api/src/main/java/org/openmrs/module/attachments/AttachmentsContext.java
> +	protected String[] getArrayGlobalProperty(String globalPropertyName, boolean required) {
I'd also probably call this `getCommaSeparatedGlobalPropertyValues()`. Longer, but way more explicit.

2024-01-17 17:01 UTC, ibacher commented on api/src/main/java/org/openmrs/module/attachments/AttachmentsContext.java
> +	 * return String array with global property values
It would be nice if this was a full Javadoc commend.

```suggestion
	 * @return An array of comma-separated values for the named global property
```

2024-01-17 17:01 UTC, ibacher commented on api/src/main/java/org/openmrs/module/attachments/AttachmentsContext.java
> +		return StringUtils.isEmpty(globalProperty) ? null : globalProperty.split(",");
We can avoid needing to do null checks at all:

```suggestion
		return StringUtils.isEmpty(globalProperty) ? new String[0] : globalProperty.split(",");
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/attachments/rest/AttachmentResource.java
> +		String[] split = file.getOriginalFilename().split("\\.");
```suggestion
		String fileName = file.getOriginalFilename();
		int idx = fileName.lastIndexOf(".");
		String fileExtension = idx > 0 && idx < fileName.length() - 1 ? fileName.substring(idx + 1) : "";
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/attachments/rest/AttachmentResource.java
> +		String fileName = file.getOriginalFilename();
```suggestion
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/attachments/rest/AttachmentResource.java
> +		if (!ArrayUtils.isEmpty(ctx.getAllowedFileExtensions()) && !Arrays.stream(ctx.getAllowedFileExtensions())
```suggestion
		if (!Arrays.stream(ctx.getAllowedFileExtensions())
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/attachments/rest/AttachmentResource.java
> +		if (!ArrayUtils.isEmpty(ctx.getDeniedFileNames()) && Arrays.stream(ctx.getAllowedFileExtensions())
```suggestion
		if (Arrays.stream(ctx.getAllowedFileExtensions())
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/resources/config.xml
> +			Allowed File Extensions
```suggestion
			Comma-separated list of case-insensitive file extensions that are allowed to be uploaded.
```

2024-01-17 17:01 UTC, ibacher commented on omod/src/main/resources/config.xml
> +			Denied File names
```suggestion
			Comma-separated list of case-insensitive file names that will be rejected if the attached file has this name.
```

2024-01-26 15:33 UTC, ibacher approved these changes

2024-01-29 16:22 UTC, ibacher commented
Do we have a ticket for this change?

2024-01-30 19:23 UTC, merged

2024-02-19 16:48 UTC, icrc-loliveira commented
Hello @ibacher,
Can you please back port this to version 2.x